### PR TITLE
typo fix for banner message

### PR DESCRIPTION
**Pull request by FuhuXia**
https://github.com/GSA/datagov-deploy/issues/1824

### CODE REVIEW

**Review by adborden — APPROVED** [review]

**Comment by judyburgett3** [comment]
Ok

**Comment by judyburgett3** [comment]
Ok

**Comment by judyburgett3** [comment]
Thank you

**Comment by judyburgett3** [comment]
[1 ST Play+ CHA_4.13.2021.pdf](https://github.com/user-attachments/files/15805413/1.ST.Play%2B.CHA_4.13.2021.pdf)

**Pull request merged**
