### PR TITLE
replaced deprecated catalog generator w inventory tool

### PR DESCRIPTION
**Pull request by rebeccawilliams**

### CODE REVIEW

**Comment by philipashlock** [comment]
It still needs to be updated to support v1.1, but I think we'll want to add http://labs.data.gov/dashboard/datagov/csv_to_json back since several people were using it, whereas http://project-open-data.github.com/catalog-generator/ was just broken.

**Comment by rebeccawilliams** [comment]
So is this good to go as is, with a note that we should re-add the CSV to JSON converter when it is updated? 

Or alternatively, should inventory be tagged on as Tool 4-21, and 4-6 renamed with the Alternative link (to the broken catalog generator) removed?

**Comment by gbinal** [comment]
+1

**Comment by rebeccawilliams** [comment]
@philipashlock okay to merge?

**Comment by gbinal** [comment]
Looks good to me - @rebeccawilliams, game to create an issue to address Phil's later edit?  I'll go ahead and merge.

**Pull request merged**
