### PR TITLE
Updated navigation on home page

### PR DESCRIPTION
**Pull request by davechod**
Added organizational construct image used by the Federal CIO Council;
organized resources into the corresponding categories; updated Open Data
Engagement section to current numbering system.

@philipashlock -- I updated the current structure per your feedback.  Let me know your thoughts.  As for the numbering scheme, I agree it could be improved but keeping the section headings is valuable.  Perhaps we can modify to [Section - Date], rather than [Section - Item#].

Preview can be found here:
https://jekit.codeforamerica.org/davechod/project-open-data.github.io/master/

### CODE REVIEW

**Comment by gbinal** [comment]
HI, @davechod.  Mind pasting a screenshot so that folks don't need to grant permissions to a third party app in order to view?

**Comment by rebeccawilliams** [comment]
Here are some screenshots: 

screen shot 2015-04-07 at 3 38 02 pm

screen shot 2015-04-07 at 3 38 11 pm

screen shot 2015-04-07 at 3 38 20 pm

screen shot 2015-04-07 at 3 38 35 pm

screen shot 2015-04-07 at 3 38 44 pm

screen shot 2015-04-07 at 3 38 50 pm

**Comment by gbinal** [comment]
I have a few concerns: 
* I'm not sure that that image is necessary there.  
* Making sure to base decisions on designs for this site on user needs, I don't know that adding the strategic priorities section brings value to the agency staff implementing the open data policy (our site's main users).

**Comment by gbinal** [comment]
I'm still trying to think through the re-ordering but think that a decision there should, again, be based on the user-friendliness of agency staff implementing this policy.  If that conflicts any with the goal of lining up these components to a separate initiative, I'm not sure we should do this.

**Comment by jlberryhill** [comment]
I like the way this organizes the information in general to align with the framework CIOC is working on. I also like the Performance section. Agree with @gbinal that image may not be needed. Seems a bit distracting to me. The Strategic Priorities section doesn't seem to fit all that well. Open Data is a small part of what these groups do, and not listing other groups makes it seem like others are main drivers of these priorities (e.g., data.gov). The priorities are directly tied to open data. Would suggest removing this section, or maybe just making it a bulleted list of the major players

**Comment by rebeccawilliams** [comment]
Agree a redesign is in order, but I think we will want to include more. @davechod, can you weigh on what should be front and center on #479?

**Pull request closed without merging**
