### PR TITLE
Public Domain & Licensing - Open and Iterative Policy Development

### PR DESCRIPTION
**Pull request by haleyvandyck**
After healthy discussion with the community here on Project Open Data and through events like the Open License Data Jam, the White House is proposing edits to M-13-13 Open Data Policy to help clarify the intention of the Open License section and address concerns raised about the lack of reference to public domain. 

This is the first pull request proposing changes to the policy document itself, and before merging we want to feedback on the language to ensure it sufficiently addresses the concerns mentioned. Let us know if there are ways we could further improve this language!

Thanks again to everyone who has participated in these open license discussions to date--it genuinely has helped us improve the quality of our guidance, and we appreciate your time and thoughtfulness.

### CODE REVIEW

**Comment by Baszz** [comment]
Good

**Comment by Baszz** [comment]
😊😊😊😊

**Comment by Baszz** [comment]
💌💌💌💌💌💌

**Comment by rebeccawilliams** [comment]
Hi All! Rebecca from OMB/OFCIO here. 

To effectively amend OMB Memorandum language, OMB would need to rescind this memo and issue a new memo. For general reference, you can track new memorandum and participate in public commenting at the following web properties:
* https://www.whitehouse.gov/omb/memoranda/
* https://policy.cio.gov/
* https://www.federalregister.gov/

Guidance for M-13-13 implementation can and should be iteratively updated on Project Open Data. The licensing concerns raised above have been incorporated into Project Open Data guidance at: https://project-open-data.cio.gov/open-licenses/. Please continue to suggest any additional guidance suggestions as Pull Requests to that guidance page.

**Comment by 76trombones** [comment]
H I Rebecca

 

I’m blocked from my .mil location at getting access to GITHUB, but am subscribed to get mailers on some things…

 

I have a couple questions, some pertaining to 

CUI [different EO  than OpenData] [eventually] metadata and schema, 

info sharing on other networks that would include classified data [another EO and revisions], and 

international info sharing [ISO’s, NATO STANAG, and GDPR for example].

 

When I look at accessLevel and rights, and I don’t see what I think tool vendors [i.e.- Titus] need for machine readable labeling… but it appears y’all have a schema and that there are issues with interoperability, i.e.- crossing domains and using metadata for ABAC [see NIST SP 800-162].

 

DOD has Instructions and Manual, and IC has Technical Data Specs… I can send you links if you’d like

 

 

r/

 

Eric E Winters

USCENTCOM CCJ6 CSUP

 

"Adequate Safeguarding, and Appropriate Sharing, of Sensitive Resources;

it's ALL about the Information"

"War is 90% Information" - attributed to Napoléon Bonaparte

**Pull request closed without merging**
