### PR TITLE
Finalize new URL

### PR DESCRIPTION
**Pull request by konklone**
Finishes the process #216 started, to update the site to point to the new URL.

* Updated `_config.yml` to change the site URL to be `https://project-open-data.cio.gov`
* Adds a `rel=canonical` link tag to point search engines et al to `https://project-open-data.cio.gov/`
* Any links that pointed to the old URL have now been changed to relative paths

A repo administrator still needs to update the URL visible at the [top of the repo page](https://github.com/project-open-data/project-open-data.github.io) to point to `https://project-open-data.cio.gov/`.

### CODE REVIEW

**Comment by gbinal** [comment]
@philipashlock - game to confirm whether we should merge this?

**Comment by konklone** [comment]
I just updated my PR to deal with merge conflicts so that it's merge-ready. It looks like most of them are because my editor strips out trailing whitespace, which conflicted with others' future edits to those paragraphs.

**Comment by konklone** [comment]
I've updated my PR and fixed merge conflicts.

It may be easiest to review my PR by looking at it with whitespace stripping removed: https://github.com/project-open-data/project-open-data.github.io/pull/373/files?w=1

**Comment by gbinal** [comment]
So..... funny story.  

There are merge conflicts again.  We're all currently within 30 feet of each other.  Want to get in the same place and finally see this one out?

**Comment by konklone** [comment]
OK, I resolved the merge conflict. It required me to [remove the line below this one](https://github.com/project-open-data/project-open-data.github.io/commit/f8a7d7f9d03ea39c52455423fa2f33b4495d3563#diff-95e8bb2c3ab91503f2d9990a8c4cfccaL15), since `license-examples` has been removed. I also [identified and fixed a merge conflict](https://github.com/project-open-data/project-open-data.github.io/commit/f977bc58fcbe9a7e44b1106b6be4f8d565257bf7) I failed to resolve last time.

How about a merge? :smiley_cat:

**Comment by konklone** [comment]
Oh, and this is the best diff URL to review my changes:

https://github.com/project-open-data/project-open-data.github.io/pull/373/files?w=1

It omits changes that are only whitespace, leaving only the substantive changes in this PR.

**Comment by gbinal** [comment]
Great - thanks a bunch and sorry for the hassle.  I'm going to go ahead and merge.

**Pull request merged**
