### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by james242**

### CODE REVIEW

**Comment by gbinal** [comment]
Since there are a range of free and open source options, I'd suggest not singling out a single commercial option.  I'd propose adding a link to csvkit but leave off json-csv.com.

**Comment by jlberryhill** [comment]
Agree with @gbinal.

**Comment by rebeccawilliams** [comment]
:+1:

**Comment by rebeccawilliams** [comment]
I removed the commercial item. Is this good to merge?

**Comment by rebeccawilliams** [comment]
Merged.

**Pull request merged**
