### PR TITLE
s/PyCSW/pycsw/g

### PR DESCRIPTION
**Pull request by tomkralidis**

### CODE REVIEW

**Comment by gbinal** [comment]
I might be missing something but I think this isn't an intentional PR.  I think we can close.

**Comment by tomkralidis** [comment]
@gbinal it is indeed intentional (minor editorial fix)

**Comment by gbinal** [comment]
Ah!  Yes.  I'm sorry about that.

**Comment by gbinal** [comment]
:+1: to merging this.

**Comment by tomkralidis** [comment]
Let me know if you require any further info to merge this PR.  Thanks.

**Comment by rebeccawilliams** [comment]
Looks good!

**Pull request merged**
